<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-24 14:54
=======
# Generated by Django 4.2.7 on 2023-11-23 12:52
>>>>>>> c114fd4df0ea3f98c0f7840d03d9edc7ff94b5af

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=255)),
=======
                ('image', models.ImageField(upload_to='product_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
>>>>>>> c114fd4df0ea3f98c0f7840d03d9edc7ff94b5af
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
