# Generated by Django 4.2.7 on 2023-11-28 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_created_at_alter_cartitem_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 11, 28)),
        ),
    ]
