# Generated by Django 4.2.7 on 2023-11-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('cart', '0003_alter_cart_created_at'),
    ]

    operations = [
    ]
