# Generated by Django 4.2.7 on 2023-11-30 08:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 8, 35, 47, 861003, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_to_cart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
