# Generated by Django 4.2.7 on 2023-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_model_email_user_model_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
        ),
    ]
