# Generated by Django 4.2.7 on 2023-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
